### ISSUE TITLE
Vendors should not be included!

### ISSUE THREAD

**Issue by Raikia** [ColorlibHQ/gentelella#348]
The vendor scripts should not be included with this package.  When you "bower install" this package just for the CSS/JS portions, its not good to have all the other 3rd party parts in it as well.  If people want them, they would include it in their own bower file and have the latest versions.

**Comment by AndreiCN** [comment]
Hi there @Raikia , 

Thak you for the suggestion, we'll take that into consideration, thank you !

**Comment by fps01** [comment]
@AndreiCN , Hello.
What news about this issue?
I approve @Raikia. We  can install all required packages from bower. It makes repository size smaller than now.

**Comment by AndreiCN** [comment]
Working on a solution @fps01 , thank you !

**Comment by fps01** [comment]
@AndreiCN, thanks for information! Then I look forward to it.

**Comment by mtangoo** [comment]
@AndreiCN thanks for considering this issue. I wanted to stress the importance of the issue itself.
Can you point steps one need to take to fix this issue?

**Comment by krzysiekpiasecki** [comment]
I'm totally disagree with this task. This is the application and it should provide always locked dependencies on master. When I want to develop i should work on the same dependencies as at master.

In bower manifest are requirements like: ```"flot.orderbars": "*"```. It's a really bad practise.

IMO to remove vendor files the bower dependencies must be locked and eventually updated when tests are passed.

**Comment by Raikia** [comment]
@krzysiekpiasecki This is a web template project where people will take the theme and not use even remotely all of the libraries included for the example template demonstration.  On top of that, this is the _entire_ reason a bower file exists at all.  if you want the third party libraries installed, you would run "bower install". 

Having the option of installing 93 MBs of libraries vs not having an option at all is a huge difference. 

There is a reason everyone recommends ignoring the vendors directory for this exact reason: http://bfy.tw/D21Z

**Comment by krzysiekpiasecki** [comment]
@Raikia Maybe because of my language, but you just don't understand me. Every one who knows what is dependency manager, knows also that vendors must no be a part of the project. No need to use google ... On the other side everyone knows that when collaborating dependencies should be locked and tests are required.

Vendor dir should be removed. It's clear, but the dependencies in manifest files must be locked. 

On the margins, why are you expected, that i want have a bower? You wrote:
> This is a web template project

Without bower and with current state of this project this template will be not runnable.

**Comment by mtangoo** [comment]
@krzysiekpiasecki I think @Raikia did not understand what you mean because you commented on wrong issue. AFAIU, you mean using * instead of locking to version x.y.z is a bad idea which I don't think anyone contests as dependencies can change with broken backward compatibility.

I suggest you open new issue on that so that we avoid confusion on this specific issue.
Peace...

**Comment by Light-Gao** [comment]
I think vendors should be kept.  
Maybe it's the case that I'm not a professional front-end programmer. But I still want to use this template in my project. So I want a full package which includes all js/css/img files I need.  
But I suggest the author could explain this in README part of this project. Maybe that would make it more accurate.
