### ISSUE TITLE
Multi-level doesn't work in mobile or with narrow menu

### ISSUE THREAD

**Issue by jamiesonbecker** [ColorlibHQ/gentelella#415]
Awesome template! Minor flaw where multi-level doesn't work in mobile or with narrow menu.

How to reproduce:

1. enable mobile view in devtools (or click icon to switch from nav-md to nav-sm)
2. click multilevel (to see the popout menu)
3. click the second "level one" dropdown
4. whole popout menu closes/disappears

This only occurs on mobile or narrow (nav-sm), not desktop view.

**Comment by steinkem** [comment]
I can second this issue, we have a go-live in a couple months and would love to see this fixed before then if at all possible!  TIA!

**Comment by AndreiCN** [comment]
Thank you for pointing this out, we will take care of it as soon as possible.

**Comment by philipcj** [comment]
Why have you closed it, it hasn't been fixed as of October? Surely you should leave it open until you fix it? It clearly is a problem as when you click the burger to go to the narrow menu the multi level menu doesn't work, you click and nothing happens. As far as I can tell the fix is to edit custom.js around line 85 to change from this:

`
if ( $BODY.is( ".nav-sm" ) )
{
	$SIDEBAR_MENU.find( "li" ).removeClass( "active active-sm" );
	$SIDEBAR_MENU.find( "li ul" ).slideUp();
}
`

to this:

`
if ( $BODY.is( ".nav-sm" ) && !$li.parent().is('.child_menu') )
{
	$SIDEBAR_MENU.find( "li" ).removeClass( "active active-sm" );
	$SIDEBAR_MENU.find( "li ul" ).slideUp();
}
`
It may be possible to pop out again though like bootstrap does rather than slide which may look neater.

**Comment by cristianraiber** [comment]
@AndreiCN - maybe leave this one opened? You marked as duplicate but I couldn't find a copy of this issue. If it's an actual duplicate, please reply with the ticket #id number and close this one.

**Comment by AndreiCN** [comment]
@philipcj this is the same issue from #490 am I right ?

**Comment by philipcj** [comment]
Yes I think so. At first glance the solution on #490 is similar to the one I suggested also.On 31 October 2017 at 09:01 AndreiCN <notifications@github.com> wrote:@philipcj this is the same issue from #490 am I right ?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by AndreiCN** [comment]
Ok , I've marked that closed because it's solved already so this one is a duplicate but the update it's not available just yet.

**Comment by philipcj** [comment]
Great. I am going to have to consider the option of secondary level menus coming out like bootstrap does. Is there a place I can make this suggestion?

**Comment by AndreiCN** [comment]
Sounds great, you can create a PR with it.

**Comment by razvanaldea89** [comment]
A fix for the menu bug ( both responsive and desktop nav-sm ) will be available soon.
Thankyou
