### ISSUE TITLE
Dynamic table issue 

### ISSUE THREAD

**Issue by richa-singh91** [ColorlibHQ/gentelella#741]
Hi, I want to display my vendor master with the dynamic table. In my vendor master, I have around 19 column but its shows only 10 column out of 19. 
Please Help I need to display all column

**Comment by razvanaldea89** [comment]
@richa-singh91  Hello, is this still an issue or did you manage to solve it?

**Comment by sublimedatasys** [comment]
Steps :

1) Add all header for all columns :

<thead>
	<tr>
	  <th>Name</th>
	  <th>Position</th>
	  <th>Office</th>
	  <th>Age</th>
	  <th>Start date</th>
	  <th>Salary</th>
	</tr>
  </thead>
  
2) Add all data for the individual rows.

<tbody>
<tr>
  <td>Tiger Nixon</td>
  <td>System Architect</td>
  <td>Edinburgh</td>
  <td>61</td>
  <td>2011/04/25</td>
  <td>$320,800</td>
</tr>  

It should display all the data on the page. But if you are facing UI issues, my suggestion adds a horizontal scroll bar. So that UI will be proper. 

To be able to display all the columns of your table correctly you need to add “scrollX”
     Property to your DataTable method like below.
            $('#example').DataTable( {
               "scrollX": true
            } );


Please check the link I have attached : https://datatables.net/examples/basic_init/scroll_x.html
