### ISSUE TITLE
Issue with layout in IE

### ISSUE THREAD

**Issue by matcsa** [ColorlibHQ/gentelella#752]
I dont know if this has been experienced but I am finding it all over the place on my template.  When I use any browser but IE it works just fine.  The page renders as desired.  However under IE the sidebar menu over shoots its size into the main page.   How do I fix this?  Its driving me bonkers.. 

![image](https://user-images.githubusercontent.com/34149525/47170947-7950b700-d2d5-11e8-8679-058fb8aaf17c.png)

**Comment by AndreiCN** [comment]
Hi there,

Make sure you're using the latest version of IE and will work just fine.

**Comment by razvanaldea89** [comment]
@docelmo are you still facing this issue?

**Comment by docelmo** [comment]
Yes its happened in all of my testing.  I ended up fixing it by
manipulating the CSS I believe it was the block-style tag I believe.


Brian

**Comment by sublimedatasys** [comment]
In the older version of IE, many CSS breaks because of a lack of support for new CSS styling. The problem you are facing is the same and to solve it customization required. 

In Gentelella support for the latest version of IE provided. The solution to this problem is to either

Use latest browser or customize your CSS as you have already done.

**Comment by cristianraiber** [comment]
Feel free to comment on this issue if you're still facing problems and we'll reopen.
