### ISSUE TITLE
Dynamic dataTable iCheck box missing on paginations.

### ISSUE THREAD

**Issue by mward29** [ColorlibHQ/gentelella#781]
First off, thanks for building Colorlib/gentelella. Its a great project. If only I had more experience/ aptitude for frontend work.

I'm trying to work with dynamic tables and iCheck for check boxes.
The iCheck box displays properly on the first page of results.
![screen shot 2019-03-01 at 3 06 29 pm](https://user-images.githubusercontent.com/1389176/53669281-d0777880-3c33-11e9-8e84-1749ce7cb664.png)

However on other paginations it shows a default check box.
![screen shot 2019-03-01 at 3 06 43 pm](https://user-images.githubusercontent.com/1389176/53669310-e9802980-3c33-11e9-9eec-66364d7ac8c5.png)

This can also be found in the colorlib demo at https://colorlib.com/polygon/gentelella/tables_dynamic.html.
On the "Plus Table Design" data table click "next" and see a default checkbox for items.
![screen shot 2019-03-01 at 3 09 13 pm](https://user-images.githubusercontent.com/1389176/53669397-3106b580-3c34-11e9-874b-823df2ca1fd9.png)

**Comment by William-H-M** [comment]
That's because ICheck it's only applied to visible objects if not wrong, and as DataTable set the fields on `hidden` we'll need to listen to when there's a page change for that table using [`page`](https://datatables.net/reference/event/page) event.

So using as some kind of base https://github.com/ColorlibHQ/gentelella/blob/d3a8e4779e645c9cfe4b37e45ade022126e87378/build/js/custom.js#L213

This event here could be used to init the plugin.
```
$('#datatable-checkbox').on('page.dt', function() {
  $('input.flat').iCheck({
    checkboxClass: 'icheckbox_flat-green',
    radioClass: 'iradio_flat-green'
  });
});
```
Note that some test should be done by @razvanaldea89

**Comment by mward29** [comment]
@William-H-M I implemented your suggestion locally. It worked. Thanks

**Comment by cristianraiber** [comment]
Thanks @William-H-M for the help!
