### ISSUE TITLE
How to build file for production

### ISSUE THREAD

**Issue by Umudo04** [ColorlibHQ/gentelella#791]
In this template, there are many libraries to used (in `vendors` dir) and I want  to make all files to one just to include html page, is there any option about it? (I mean building css and js files).

**Comment by sublimedatasys** [comment]
Yes this is possible.

- Instead of having all the plugins in vendors directory  you can install all the dependencies via npm. Now All the plugins will be present in node_modules as a dependency.

- Second step to import all your plugin dependencies  from node_module  to a single file  "custom.js”   in your project. 

- Now you can use a single file “custom.js” in your HTML file.

**Comment by catccat** [comment]
any example?

**Comment by cristianraiber** [comment]
Example is written above. Sorry, this is not a tutorial section.
