### ISSUE TITLE
tags styles can't come out 

### ISSUE THREAD

**Issue by breeef** [ColorlibHQ/gentelella#797]
When i copied the original tags code from production/form.html as follows:
```
<div class="col-md-3 col-sm-12 col-xs-12">
                          <label >关键词</label>
                          <input id="tags_1" type="text" class="tags form-control" value="social, adverts, sales" />
</div>

<div class="col-md-3 col-sm-12 col-xs-12">
                          <label >服务</label>
                          <input id="tags_2" type="text" class="tags form-control" value="social, adverts, sales" />
</div>

<div class="col-md-3 col-sm-12 col-xs-12">
                          <label >产品</label>
                          <input id="tags_3" type="text" class="tags form-control" value="social, adverts, sales" />
                        
</div>
```
<img width="821" alt="image" src="https://user-images.githubusercontent.com/16204293/59425265-1e417680-8e08-11e9-8379-7c47f70f6ac7.png">
it can only come out the first tag style,
when i tried change the id='tags_1' to id ='other' the only one tags style also disappeared.

**Comment by thomaslwq** [comment]
Hallo,I also copy the same fille production/form.html  from the master branch.But it shows that it is normal.Maybe you can check your reference of of the source file or you can check the custom js file as show beblow because this tag is control by ID.
![image](https://user-images.githubusercontent.com/3986176/59450683-58c50680-8e3c-11e9-8879-38ddf46cbd96.png)

**Comment by breeef** [comment]
谢谢老哥！

**Comment by thomaslwq** [comment]
> 谢谢老哥！

不客气
