### ISSUE TITLE
Rails 6 webpack how include vendors?

### ISSUE THREAD

**Issue by galievruslan** [ColorlibHQ/gentelella#840]
Hello
I want to connect the gentelella template to my rails 6 project.
The project is completely empty.
Installed via yarn add gentelella.
Further in the file app / javascript / packs / application.js added
`require ("gentelella")`
But when you open any page, it gives an error that Jquery is not connected. If I understand correctly all the dependencies should have been connected from the vendors folder but this did not happen, at least for rails 6 it works for a friend.
Tell me how to properly connect all the dependencies so as not to install them manually.

**Comment by sublimedatasys** [comment]
Hello @galievruslan , 
You understood right. All the dependency are connected from vendors folder. But as i can understand from your comment, in you case the path to import dependencies in the HTML files no longer correct. 
You must change all the scripts and style path to get the template work.
for now i am closing this issue if your issue is not still resolve, feel free to reopen this one.

Thank you.
